### ISSUE TITLE
When the core network uses a non-empty encryption algorithm, the UE cannot attach correctly

### ISSUE THREAD

**Issue by liuxiaoxinxinxin** [s5uishida/free5gc_srsran_sample_config#3]
Hello, I set up the environment according to your guidance, using free5gc as the core network and srsRAN Project as the base station, with srsRAN 4G as the UE.

When using NEA0 in the free5gc core network AMF configuration file, meaning the encryption algorithm is NEA0, the UE can successfully attach (NEA0 with NIA1, NIA2 or NIA3). However, when the encryption algorithm is not NULL (like NEA1 with NIA1), the UE fails to attach. The specific reason is that the UE cannot parse the initial context setup (registration accept) sent by the core network.

We found that when the UE parses the registration accept message, the inner extended protocol discriminator it decodes is incorrect.

Have you ever had the opportunity to use encryption algorithms, or do you have any suggestions or assistance you could offer? 
Thank you!

**Comment by s5uishida** [comment]
Hi @liuxiaoxinxinxin 

Have you tried it with UERANSIM?
Also, you have asked this issue to srsRAN, so if you don't mind, how about you attach your configuration files and ask this to srsRAN again?

**Comment by liuxiaoxinxinxin** [comment]
@s5uishida 
Thanks for your reply!
I've tried with UERANSIM and everything was ok. 
I am currently reviewing the source code of srsran and trying to identify where the issues might be. I am also awaiting a response from srsran. 
By the way, I have set up the environment based on several of your repositories, and they have been very helpful. Thank you!
